assets/travelling.js
index.html

Reverts volfclub/travellings#15
似乎有故障导致无法跳转

Revert "同步更改，并且加入判斷"

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/973 
fixed https://github.com/travellings-link/travellings/issues/1083

修改网站【六个周】新增网站【iCooper Blog】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1103

添加【Harryの心阁】

---

.github/CODEOWNERS
index.html
nowsh/index.html

累加修改2022.07.26

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1110 ,fixes https://github.com/travellings-link/travellings/issues/1115, fixes https://github.com/travellings-link/travellings/issues/1081, fixes https://github.com/travellings-link/travellings/issues/1114, fixes https://github.com/travellings-link/travellings/issues/1116
等过一会再一起合并。

添加【Leonus】【澄沨的漫游茶记】【闪闪の小窝】【落星屋】【RK-Blog】

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1070, fixes https://github.com/travellings-link/travellings/issues/1118, fixes https://github.com/travellings-link/travellings/issues/874

删除【WikiMimo】、修改【304号凝雀】、修改【459号】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1130

添加【Xlencoの小窝】【FuBaooo 博客】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1134

恢复【橘夜庭|霂森西】

---

member.md

fixed https://github.com/travellings-link/travellings/issues/1134

修正【橘夜庭|霂森西】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1091

添加【Bluemangoo's Blog】

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1142, fixes https://github.com/travellings-link/travellings/issues/1146

添加【序炁的博客】【圆周率的博客】【Hairy's Blog】【ShootZone】

---

assets/travelling.js
member.md

fixes #1143 , fixes #1154 , fixes #61

添加【强曰为道】【CheeseburgerIM's Blog】并恢复48【Zhou‘s Blog】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1144

添加【SinGO博客】

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1162, fixes https://github.com/travellings-link/travellings/issues/1164
https://github.com/travellings-link/travellings/issues/959

添加【小明的博客】【嘉嘉的博客】并撤下521【梦境花园】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1158 https://github.com/travellings-link/travellings/issues/1163

添加【怡然一记】【WindowsRegeditのsite】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1167

添加【Niute Fony】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1175 https://github.com/travellings-link/travellings/issues/1174 https://github.com/travellings-link/travellings/issues/1173 https://github.com/travellings-link/travellings/issues/1171

添加【fffzlfk's Blog】【Braindance】【兔儿轩的小空间】【LYXの小破站】

---

assets/travelling.js
member.md

https://www.hicool.icu 域名已不再是原站点

撤下346【Hicool嗨酷】

---

assets/travelling.js
member.md

修改了travelling.js中urls 0，110，586的地址
fixed https://github.com/travellings-link/travellings/issues/1193
fixed https://github.com/travellings-link/travellings/issues/1192
fixed https://github.com/travellings-link/travellings/issues/1191
fixed https://github.com/travellings-link/travellings/issues/1190
fixed https://github.com/travellings-link/travellings/issues/1186

添加【小莫唐尼】【长街短梦】【元のDiary】【八荒山人的博客】【Alone' Blog】，修改了travelling.js

---

assets/travelling.js
member.md

#804 #301 https://github.com/travellings-link/travellings/issues/1011

撤下失效站点 182[鲸一],346[Hicool嗨酷],487[JerryDodo私日记],561[Prk博客]

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1198

更新 `[554]摸鱼中` 站点域名并撤下`[385]三水非冰`

---

.github/CODEOWNERS

修改 CODEOWNERS

---

assets/travelling.js

fix: discussion #1214 & #1205

---

assets/travelling.js
member.md

添加【loquy】【浅溪-Ling Chen's blog】【武恩赐博客】【BinGo's Blog】
fixed https://github.com/travellings-link/travellings/issues/1225
fixed https://github.com/travellings-link/travellings/issues/1224
fixed https://github.com/travellings-link/travellings/issues/1222
fixed https://github.com/travellings-link/travellings/issues/1216

添加【loquy】【浅溪-Ling Chen's blog】【武恩赐博客】【BinGo's Blog】

---

assets/travelling.js
member.md

fixed https://github.com/travellings-link/travellings/issues/1230

添加【Mycpen】

---

assets/travelling.js
member.md

已添加
【Ace浅末】fixed https://github.com/travellings-link/travellings/issues/1253
【习物志】fixed https://github.com/travellings-link/travellings/issues/1255
移除失效网站【殆己】fixed https://github.com/travellings-link/travellings/issues/10

新增网站并移除失效网站

---

assets/travelling.js
member.md

* https://github.com/travellings-link/travellings/issues/1264

修改 SinGO博客

---

README.md

添加`LeonShaw`至维护者名单

---

assets/travelling.js
index.html
member.md

fixed #1362
fixed #1364
fixed #1366
fixed #1368
fixed #1370
fixed #1371
fixed #1372
fixed #1373

添加网站和JS跳转代码

---

assets/travelling.js
member.md

对序号为 1 - 99 的博客进行巡查，删除 5 个无法访问或移除开往链接的博客，提示 34 个博客更新开往链接至最新

巡查 1 - 99 的博客

---

assets/travelling.js
member.md

fixes https://github.com/travellings-link/travellings/issues/1432, fixes https://github.com/travellings-link/travellings/issues/1442, fixes https://github.com/travellings-link/travellings/issues/1447, fixes https://github.com/travellings-link/travellings/issues/1448, fixes https://github.com/travellings-link/travellings/issues/1450, fixes https://github.com/travellings-link/travellings/issues/1451, fixes https://github.com/travellings-link/travellings/issues/1453, fixes https://github.com/travellings-link/travellings/issues/1454, fixes https://github.com/travellings-link/travellings/issues/1455, fixes https://github.com/travellings-link/travellings/issues/1457

处理堆积的已审核通过的成员网站

---

docs/intro.md

typo: remove md suffix

---

docusaurus.config.js

首页有个 typo 就先修了。
~~能否顺便处理一下 #1466 （x~~

fix: typo start -> star

---

.github/workflows/issue-closed.yml

ci: Optimize `remove-labels` for auto close issue

---

.github/workflows/issue-pass.yml

ci: Add auto send approval message

---

.github/workflows/updata.yml

@BLxcwg666
Co-Authored-By: BLxcwg666 <huixcwg@gmail.com>

workflow(update): 自动将仓库同步到服务器

---

.github/ISSUE_TEMPLATE/update.yml

chore: 增加申请变更 issue 模板

---

.github/ISSUE_TEMPLATE/beta.yml

[Chore-Git] 将内容方向修改为单选题

---

static/go.html

为默认的go.html添加了深色模式适配，以及深色模式过渡动画。

perf: Add dark mode support to go.html

---

src/pages/index.module.css

pref: Add Gaussian blur to enhance the readability of the text

---

docs/join.md

Change the original observation period to audit time, and optimize some contents at the same time.

Modify some contents.

---

.github/workflows/issue-labeled.yml

ci: Update issue-labeled.yml

---

static/go.html

perf: 删除多余的css

---

.github/workflows/issue-labeled.yml
static/coder-1024.html
static/go.html
static/plain.html

cookie的名称为preference，值之后设置为某个标签（多个标签要考虑标签的顺序，我们弄单个标签规避这个问题）

获取cookie并配置跳转地址

---

static/go.html

Jump to add analysis code

---

static/plain.html

Add analysis code

---

public/coder-1024.html

fix: coder-1024.html

---

.vitepress/config.mts

修复点击顶栏的多语言问题

---

en_US/README.md
en_US/docs/join.md
en_US/docs/toyou.md
zh_HK/README.md
zh_TW/README.md

不是你们是真没活了啊就这么个东西拿机翻半小时整完的事非要这么费劲吗

revert: #2148

---

.github/workflows/issue-labeled.yml

The PR needs to be noticed whether the code is changed correctly.

workflow(label): 添加TG群链接并删除社群通知

---

.vitepress/config.mts

I don't know whether it is correct.

Update(config): Use schema

---

blog/202405.md
en_US/blog/202405.md
zh_TW/blog/202405.md

本次修改内容：
1.修改标题：标题内容顺序与正文内容顺序相同
2.内容修订：对于一些内容的语序与标点进行修改
非常感谢@gxres042 @linlinzzo 对于初稿的帮助，十分感谢！
（如果对于本次修订有任何意见，也请及时告知！）

Doc: Fix grammar problems in May blog

---

.github/ISSUE_TEMPLATE/beta.yml

考虑到有人修改了模板内容导致添加进数据库时出错，特此修改模板。

修改申请的 TEMPLATE

---

.vitepress/config/en_US.mts
.vitepress/config/zh_CN.mts
.vitepress/config/zh_TW.mts

由于众所周知的问题，爱发电链接afdian.net在国内的访问情况一言难尽，因此本PR将afdian.net改为afdian.com

fix:Change the afdian link

---

.vitepress/theme/components/maintainers.ts

Hey，由于一些个人原因，我无法胜任开往维护组的相关工作，自2024/9/20启自愿退出开往。非常感谢各位对于我的帮助！

[Docs] Say bye~

---

blog/202412.md
en_US/blog/202412.md
zh_TW/blog/202412.md

hey！好久不见，由于一些个人原因，虽然退出了开往维护组，但如果我有空或许还是会给开往改改稿子，也非常感谢开往维护组能为我提供了一个机会去学习相关技术，同时也认识了很多大佬。
本次PR主要更改的是12月份blog
1. 修订文章标点问题（比如缺少“（）”或者“，”）
2. 优化文段逻辑 
3. 优化部分用处不当
~~但其实都是一些没啥大用的优化，这篇文章还算是工整的了~~

[Doc] December blog language optimization

---

.github/workflows/deploy-cloudflare.yml
package.json
wrangler.toml

Deploy our official website to Cloudflare Workers for global visitors.

deploy to cloudflare workers (global)

---

.github/workflows/issue-closed.yml

feat: auto remove label 审核通过

---

public/go-robot.html

机器人对话版的开往跳转页面
